# -*- coding: utf-8 -*-
"""Characterise the SN5 save cipher before hunting the decrypt loop.

Facts so far: DATA.BIN is 170144 B (0x298A0), entropy 7.999 bits/byte, and
99.6% of bytes differ between any two saves. That is consistent with a stream
or block cipher re-keyed per save, and rules out "mostly plaintext with a few
progress fields".

Three cheap tests separate the candidates:

  T1  XOR of two ciphertexts. If both saves were encrypted with the SAME key
      and the plaintexts are merely different progress states, then
      c1^c2 = p1^p2 (keystream cancels). Two similar plaintexts XOR to mostly
      zeros, so the XOR blob would be LOW entropy with runs of 00. If the XOR
      is itself high-entropy, the keystream differs per save and no
      same-key differential attack is available.

  T2  Repeated blocks WITHIN one file. ECB reuses ciphertext for identical
      plaintext blocks, so a 170 KB save with any repetition (lots of zeros or
      repeated stat tables in plaintext) shows duplicate 8/16-byte blocks. No
      duplicates rules ECB out and is consistent with CTR/CBC or a stream
      cipher. Note 170144 % 16 == 0 and % 8 == 0, so 8- and 16-byte block
      ciphers are both size-legal.

  T3  Autocorrelation / index-of-coincidence. A stream cipher generated by a
      simple LCG or a repeating key shows periodicity; a real PRNG or block
      cipher does not.
"""
import collections
import math
import os

SD = r'D:\Video_Game\Emulator\PSP\PPSSPP 1.20\ppsspp\memstick\PSP\SAVEDATA'
F = {
    'USA46': os.path.join(SD, 'ULUS10656SN5GAME46', 'DATA.BIN'),
    'USA47': os.path.join(SD, 'ULUS10656SN5GAME47', 'DATA.BIN'),
    'JP00':  os.path.join(SD, 'NPJH50696SN5GAME00', 'DATA.BIN'),
    'JP01':  os.path.join(SD, 'NPJH50696SN5GAME01', 'DATA.BIN'),
    'JP05':  os.path.join(SD, 'NPJH50696SN5GAME05', 'DATA.BIN'),
    'SYSUSA': os.path.join(SD, 'ULUS10656SN5SYSTEM', 'DATA.BIN'),
    'SYSJP':  os.path.join(SD, 'NPJH50696SN5SYSTEM', 'DATA.BIN'),
}


def ent(b):
    if not b:
        return 0.0
    c = collections.Counter(b)
    n = len(b)
    return -sum((v / n) * math.log2(v / n) for v in c.values())


d = {}
for k, p in F.items():
    if os.path.isfile(p):
        d[k] = open(p, 'rb').read()
    else:
        print('MISSING %-8s %s' % (k, p))

print('=== sizes ===')
for k, b in d.items():
    print('  %-8s %7d  (0x%X)  %%8=%d %%16=%d  %%4=%d  ent=%.3f'
          % (k, len(b), len(b), len(b) % 8, len(b) % 16, len(b) % 4, ent(b)))

def maxrun(x):
    best = cur = 0
    for by in x:
        cur = cur + 1 if by == 0 else 0
        if cur > best:
            best = cur
    return best


print('\n=== T1: XOR of same-region pairs (keystream cancellation test) ===')
pairs = [('USA46', 'USA47'), ('JP00', 'JP01'), ('JP00', 'JP05'),
         ('USA46', 'JP00'), ('SYSUSA', 'SYSJP')]
for a, b in pairs:
    if a not in d or b not in d:
        continue
    x = bytes(p ^ q for p, q in zip(d[a], d[b]))
    z = x.count(0)
    print('  %-7s ^ %-7s : ent=%.3f  zero%%=%.2f  longest zero run=%d'
          % (a, b, ent(x), 100.0 * z / len(x), maxrun(x)))


print('\n=== T2: repeated blocks within each file ===')
for k, b in d.items():
    for bs in (8, 16, 32):
        blocks = collections.Counter(b[i:i + bs] for i in range(0, len(b) - bs + 1, bs))
        dup = sum(c - 1 for c in blocks.values() if c > 1)
        print('  %-8s bs=%2d : %6d blocks, %5d duplicate instances'
              % (k, bs, len(blocks), dup))

print('\n=== T3: periodicity of the byte stream (same-key streams repeat) ===')
for k, b in d.items():
    hits = []
    for period in (4, 8, 16, 32, 64, 128, 256):
        # fraction of positions where byte[i] == byte[i+period]
        same = sum(1 for i in range(0, len(b) - period) if b[i] == b[i + period])
        frac = same / (len(b) - period)
        hits.append('p%-4d %.4f' % (period, frac))
    print('  %-8s %s' % (k, '  '.join(hits)))
print('  (random baseline is ~1/256 = 0.0039)')

print('\n=== T4: value distribution sanity (uniform => real cipher) ===')
for k, b in d.items():
    c = collections.Counter(b)
    exp = len(b) / 256.0
    chi = sum((c.get(i, 0) - exp) ** 2 / exp for i in range(256))
    print('  %-8s chi2=%.1f (df=255, expect ~255 if uniform)' % (k, chi))
print('DONE')
